#!/usr/bin/env python3
"""Claude Code PR Review Agent.

A skill that reviews GitHub pull requests and produces a structured
Markdown review with summary, identified risks, improvement suggestions,
and a confidence score.

CLI usage:
  python3 review.py --pr https://github.com/owner/repo/pull/123
  python3 review.py --pr 123 --repo owner/repo

Requires:
  - GITHUB_TOKEN environment variable (GitHub personal access token)
  - ANTHROPIC_API_KEY environment variable (for using Claude via API)
"""

import argparse
import json
import os
import re
import sys
import urllib.request
import urllib.error
from typing import Optional
from dataclasses import dataclass, field


@dataclass
class PRReview:
    """Structured PR review result."""
    pr_url: str
    pr_title: str = ""
    pr_author: str = ""
    summary: str = ""
    risks: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)
    confidence: str = "Medium"

    def to_markdown(self) -> str:
        """Render the review as structured Markdown."""
        lines = [
            "## 🤖 PR Review",
            "",
            f"> **PR**: [{self.pr_title}]({self.pr_url})",
            f"> **Author**: @{self.pr_author}" if self.pr_author else "",
            "",
            "---",
            "",
            "### 📋 Summary of Changes",
            "",
            self.summary,
            "",
            "### ⚠️ Identified Risks",
            "",
        ]
        if self.risks:
            for r in self.risks:
                lines.append(f"- {r}")
        else:
            lines.append("*No significant risks identified.*")

        lines += [
            "",
            "### 💡 Improvement Suggestions",
            "",
        ]
        if self.suggestions:
            for s in self.suggestions:
                lines.append(f"- {s}")
        else:
            lines.append("*No improvement suggestions.*")

        lines += [
            "",
            "---",
            "",
            f"### ✅ Confidence Score: **{self.confidence}**",
            "",
            f"*Review generated by PR Review Agent*",
        ]
        return "\n".join(line for line in lines if line.strip() or line == "")

    def to_json(self) -> str:
        return json.dumps({
            "pr_url": self.pr_url,
            "pr_title": self.pr_title,
            "pr_author": self.pr_author,
            "summary": self.summary,
            "risks": self.risks,
            "suggestions": self.suggestions,
            "confidence": self.confidence,
        }, ensure_ascii=False, indent=2)

    def save(self, path: str) -> None:
        """Save markdown review to file."""
        with open(path, "w", encoding="utf-8") as f:
            f.write(self.to_markdown())

    @classmethod
    def from_dict(cls, d: dict, pr_url: str) -> "PRReview":
        return cls(
            pr_url=pr_url,
            pr_title=d.get("title", ""),
            pr_author=d.get("author", ""),
            summary=d.get("summary", ""),
            risks=d.get("risks", []),
            suggestions=d.get("suggestions", []),
            confidence=d.get("confidence", "Medium"),
        )


# ---------------------------------------------------------------------------
# GitHub helpers
# ---------------------------------------------------------------------------

GITHUB_API = "https://api.github.com"
PR_PATTERN = re.compile(
    r"(?:https?://github\.com/)?([^/]+)/([^/]+)/pull/(\d+)"
)


def parse_pr_url(url: str) -> tuple[str, str, int]:
    """Parse a PR URL or PR number+repo combo."""
    m = PR_PATTERN.match(url)
    if m:
        return m.group(1), m.group(2), int(m.group(3))
    # Try "owner/repo" + number format
    parts = url.split("/")
    if len(parts) == 3 and parts[2].isdigit():
        return parts[0], parts[1], int(parts[2])
    raise ValueError(
        f"Cannot parse PR from: {url}\n"
        f"Expected formats:\n"
        f"  https://github.com/owner/repo/pull/123\n"
        f"  owner/repo/123"
    )


def github_get(path: str) -> dict:
    """Make an authenticated GET request to the GitHub API."""
    token = os.environ.get("GITHUB_TOKEN", "")
    headers = {
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "pr-review-agent",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"

    url = f"{GITHUB_API}/{path.lstrip('/')}"
    req = urllib.request.Request(url, headers=headers)

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        body = e.read().decode() if e.fp else ""
        raise RuntimeError(
            f"GitHub API error {e.code}: {e.reason}\n{body[:500]}"
        )


def fetch_pr_info(owner: str, repo: str, pr_number: int) -> dict:
    """Fetch PR metadata from GitHub."""
    data = github_get(f"repos/{owner}/{repo}/pulls/{pr_number}")
    return {
        "title": data.get("title", ""),
        "author": data.get("user", {}).get("login", ""),
        "body": data.get("body", ""),
        "state": data.get("state", ""),
    }


def fetch_pr_diff(owner: str, repo: str, pr_number: int) -> str:
    """Fetch the PR diff text using the diff endpoint."""
    token = os.environ.get("GITHUB_TOKEN", "")
    headers = {
        "Accept": "application/vnd.github.v3.diff",
        "User-Agent": "pr-review-agent",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"

    url = f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}"
    req = urllib.request.Request(url, headers=headers)

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as e:
        body = e.read().decode() if e.fp else ""
        # Fall back: fetch files individually
        files = github_get(f"repos/{owner}/{repo}/pulls/{pr_number}/files")
        parts = []
        for f in files:
            patch = f.get("patch", "")
            if patch:
                parts.append(f"diff --git a/{f['filename']} b/{f['filename']}")
                parts.append(patch)
        return "\n".join(parts)


# ---------------------------------------------------------------------------
# AI analysis
# ---------------------------------------------------------------------------

def analyze_with_claude(diff: str, pr_info: dict) -> dict:
    """Use Claude to analyze a PR diff and produce a structured review.

    Falls back to built-in heuristics if ANTHROPIC_API_KEY is not set.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")

    if api_key:
        return _analyze_via_api(api_key, diff, pr_info)

    return _analyze_heuristic(diff, pr_info)


def _analyze_via_api(api_key: str, diff: str, pr_info: dict) -> dict:
    """Call Anthropic API to get a structured review."""
    # Truncate diff to avoid hitting token limits
    max_diff_chars = 60000
    truncated_diff = diff[:max_diff_chars]
    if len(diff) > max_diff_chars:
        truncated_diff += "\n# ... (diff truncated due to length)"

    prompt = f"""You are a thorough code reviewer. Review the following GitHub Pull Request.

PR Title: {pr_info.get('title', 'N/A')}
PR Author: @{pr_info.get('author', 'unknown')}

Analyze the diff below and produce a JSON object with exactly these keys:
- "summary": A 2-3 sentence summary of what this PR does.
- "risks": An array of strings, each describing a specific risk or concern. Be honest but constructive.
- "suggestions": An array of strings, each suggesting a concrete improvement.
- "confidence": One of "Low", "Medium", or "High" indicating your confidence in this review. Consider factors like diff size, complexity, test coverage implied by the diff.

Return ONLY a valid JSON object, no other text.

DIFF:
```diff
{truncated_diff}
```"""

    data = json.dumps({
        "model": "claude-sonnet-4-20250514",
        "max_tokens": 4096,
        "messages": [{"role": "user", "content": prompt}],
    }).encode()

    headers = {
        "Content-Type": "application/json",
        "x-api-key": api_key,
        "anthropic-version": "2023-06-01",
    }

    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=data,
        headers=headers,
    )

    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            result = json.loads(resp.read().decode())
        content = result.get("content", [{}])[0].get("text", "{}")
        # Extract JSON from the response (handle markdown code fences)
        json_match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", content, re.DOTALL)
        if json_match:
            content = json_match.group(1)
        else:
            # Try to find JSON object directly
            json_match = re.search(r"(\{.*\})", content, re.DOTALL)
            if json_match:
                content = json_match.group(1)
        return json.loads(content)
    except Exception as e:
        return _analyze_heuristic(diff, pr_info)


def _analyze_heuristic(diff: str, pr_info: dict) -> dict:
    """Built-in heuristic analysis when Claude API is unavailable.

    Gives a reasonable review based on diff patterns.
    """
    risks = []
    suggestions = []

    # Count changed files and lines
    files_changed = len(set(
        line for line in diff.split("\n")
        if line.startswith("diff --git")
    ))
    added_lines = sum(1 for line in diff.split("\n") if line.startswith("+") and not line.startswith("+++"))
    removed_lines = sum(1 for line in diff.split("\n") if line.startswith("-") and not line.startswith("---"))

    # Pattern-based risk detection
    risk_patterns = [
        (r"(?i)(password|secret|token|api_key|api[-_]?key)\s*=\s*['\"][^'\"]+['\"]",
         "Possible hardcoded credential detected"),
        (r"(?i)(TODO|FIXME|HACK|XXX|WORKAROUND)",
         "Contains TODO/FIXME markers that may indicate incomplete work"),
        (r"(?i)\bprint\s*\(|console\.log\b",
         "Debug print/console.log statements left in code"),
        (r"(?i)(DROP\s+TABLE|TRUNCATE|DELETE\s+FROM)",
         "Destructive database operations detected"),
        (r"(?i)exec\s*\(|eval\s*\(|subprocess\.",
         "Dynamic code execution detected — review security implications"),
        (r"(\+.*){200,}",  # lines with 200+ chars added
         "Very long lines detected — consider breaking them up"),
        (r"(?i)(n\+1|N\+1|select\s+\*\s+from)",
         "Potential N+1 query pattern detected"),
        (r"#\s*(type:\s*ignore|type:\s*ignore\[)",
         "Type ignore comments suppress type checking"),
    ]

    for pattern, risk_msg in risk_patterns:
        if re.search(pattern, diff):
            risks.append(risk_msg)

    # Size-based assessments
    if files_changed > 15:
        risks.append(f"Large PR with {files_changed} files changed — consider splitting into smaller PRs")
    if added_lines > 500:
        risks.append(f"Large diff ({added_lines} lines added) — hard to review thoroughly")

    if added_lines == 0 and removed_lines > 0:
        suggestions.append("Consider explaining why code is being removed without replacements")
    if files_changed <= 3:
        suggestions.append("Well-scoped PR — easy to review")

    # Generate summary
    if files_changed == 0:
        summary = "This PR makes no file changes. It may be a documentation-only or metadata update."
    elif files_changed == 1:
        summary = f"This PR modifies 1 file with {added_lines} additions and {removed_lines} deletions."
    else:
        summary = (f"This PR modifies {files_changed} files with {added_lines} additions "
                   f"and {removed_lines} deletions. "
                   f"{'It touches a significant amount of code.' if added_lines > 200 else 'The changes are relatively contained.'}")

    # Confidence
    if files_changed > 20 or added_lines > 1000:
        confidence = "Low"
    elif files_changed > 10 or added_lines > 300:
        confidence = "Medium"
    else:
        confidence = "High"

    return {
        "summary": summary,
        "risks": list(set(risks)),
        "suggestions": list(set(suggestions)),
        "confidence": confidence,
        "title": pr_info.get("title", ""),
        "author": pr_info.get("author", ""),
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Review a GitHub PR and produce structured Markdown output."
    )
    parser.add_argument(
        "--pr", required=True,
        help="PR URL (https://github.com/owner/repo/pull/123) or owner/repo/number"
    )
    parser.add_argument(
        "--output", "-o",
        help="Output file path (default: stdout)"
    )
    parser.add_argument(
        "--format", choices=["markdown", "json"], default="markdown",
        help="Output format (default: markdown)"
    )
    parser.add_argument(
        "--no-fallback", action="store_true",
        help="Fail if Claude API is not available instead of using heuristic analysis"
    )
    args = parser.parse_args()

    # Parse PR
    try:
        owner, repo, pr_number = parse_pr_url(args.pr)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    pr_url = f"https://github.com/{owner}/{repo}/pull/{pr_number}"

    # Fetch PR info and diff
    print(f"🔍 Fetching PR #{pr_number} from {owner}/{repo}...", file=sys.stderr)
    try:
        pr_info = fetch_pr_info(owner, repo, pr_number)
        diff = fetch_pr_diff(owner, repo, pr_number)
    except RuntimeError as e:
        print(f"Error fetching PR: {e}", file=sys.stderr)
        sys.exit(1)

    if not diff:
        print("Error: PR has no diff (empty or already merged)", file=sys.stderr)
        sys.exit(1)

    diff_size = len(diff)
    file_count = len([l for l in diff.split("\n") if l.startswith("diff --git")])
    print(f"📄 Diff size: {diff_size:,} bytes across {file_count} files",
          file=sys.stderr)

    # Analyze
    print("🧠 Analyzing...", file=sys.stderr)
    has_api = bool(os.environ.get("ANTHROPIC_API_KEY"))
    if not has_api and args.no_fallback:
        print("Error: ANTHROPIC_API_KEY not set and --no-fallback specified",
              file=sys.stderr)
        sys.exit(1)

    if has_api:
        print("🤖 Using Claude API for analysis", file=sys.stderr)
    else:
        print("⚙️  ANTHROPIC_API_KEY not set, using heuristic analysis", file=sys.stderr)
        print("💡 Set ANTHROPIC_API_KEY for AI-powered reviews", file=sys.stderr)

    result = analyze_with_claude(diff, pr_info)
    review = PRReview.from_dict(result, pr_url)

    # Output
    output = review.to_markdown() if args.format == "markdown" else review.to_json()

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(output)
        print(f"✅ Review written to {args.output}", file=sys.stderr)
    else:
        print(output)

    sys.exit(0)


if __name__ == "__main__":
    main()
